name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Push source to Hugging Face Spaces
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.email "adivid198986@gmail.com"
          git config user.name  "aditya-rAj19"

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://aditya-rAj19:${HF_TOKEN}@huggingface.co/spaces/aditya-rAj19/FaceSWAP || true
          git push hf main --force
